### ISSUE TITLE
breast-feeding emoji, v13 2020

### ISSUE THREAD

**Issue by ccorcos** [iamcal/emoji-data#169]
🤱 | breast-feeding | :breast-feeding | 38,56

How can we update this for the latest emojis? https://unicodey.com/emoji-data/table.htm

Also, any way to determine what platforms support which emojis?

**Comment by EtienneLem** [comment]
> 🤱 | breast-feeding | :breast-feeding | 38,56

According to https://emojipedia.org/breast-feeding `:breast-feeding:` has been introduced in 2017 as part of Emoji 5.0. emoji-data is built against https://unicodey.com/emoji-data/table.htm, so if the emoji can be found there it’s most likely included in `emoji.json`.

Validated on https://missive.github.io/emoji-mart (using latest emoji-data), I can find `:breast-feeding:`

> How can we update this for the latest emojis? https://unicodey.com/emoji-data/table.htm

I believe Emoji 12.1 is the latest published version. Emoji 13 has yet to be released: https://emojipedia.org/emoji-13.0

> Also, any way to determine what platforms support which emojis?

 I don’t know if it would realistically be possible to keep track of. As far as I can tell it depends on both the platform and the browsers, at least it used to.

**Comment by jwheare** [comment]
The emoji version numbers in the data can be used to do *some* limited degree of platform support:

5.0 supported in macos high sierra (10.13) and later
11.0 supported in macos mojave (10.14) and later
12.0/12.1 supported in macos catalina (10.15) and later

In the browser, detection on Windows is harder because the user agent string has stayed the same for every minor version of Windows 10 that has subsequently added more native emoji support. 12.1 emoji are also not yet supported in Windows 10.

On linux it's harder still because it largely depends on a certain font being installed (Google's Noto Color Emoji), rather than distro/version number. And the font could be an older version.

Note also that there are exceptions, e.g.
* no version of Windows currently natively supports any country flag emojis, despite them existing in emoji 2.0.
* The UN flag is only supported on macos mojave or later, despite being a 4.0 emoji
* medical_symbol, female_sign, male_sign are not yet natively supported on any version of macos

A reliable method probably involves trying to render various emoji from different releases in a canvas element and then inspecting the pixel values to see if they have any colour values. I have not implemented this personally though.

**Comment by ccorcos** [comment]
Oh, I'm confusing that with ["woman feeding baby"](https://emojipedia.org/woman-feeding-baby/). 

Thanks for the help!

**Comment by ccorcos** [comment]
Also, any thoughts on how to sensibly order the emojis? Something similar to the Apple Emoji picker... I also noticed that Apple has slightly different categories.

**Comment by EtienneLem** [comment]
`sort_order` should be pretty much the same order as Apple, or close enough that you don’t really notice that much of a difference. Especially if you can search.

The new categories were a bit of a mystery to me, couldn’t tell where these were coming from. Since the latest version, **Smileys & People** has been divided into **Smileys & Emotion** and **People & Body**. Can’t just merge the emojis because the `sort_order` is per category. That being said, given these 2 new categories, if you take the first 114 emojis of the first one, all of the second one and finally the rest of first, you get a similar order than Apple and can make that a single **Smileys & People** category again. Here’s how we did it https://github.com/missive/emoji-mart/blob/master/scripts/build.js#L122-L129. It’s not perfect, but haven’t had a single complaint yet.

**Comment by ccorcos** [comment]
I see. You're correct. `sort_order` is exactly what I'm looking for. Thanks!
