### ISSUE TITLE
No UNPKG version for 6.1.1?

### ISSUE THREAD

**Issue by yagudaev** [iamcal/emoji-data#193]
Seems like the UNPKG doesn't include version 6.1.1? 

I've never used unpkg much, did something with UMD change it this package to prevent it from automatically detecting a new version?

Only reason I say that is because https://github.com/missive/emoji-mart uses spritesheet from unpackaged. As I was trying to upgrade the component to support this lib I noticed it.

**Comment by iamcal** [comment]
It looks like the 6.1.1 packages for emoji-datasource-* (the image packages, not the base package) did not get correctly published to NPM.

This is fixed in 7.0.0/7.0.1:
https://unpkg.com/emoji-datasource-apple@7.0.1/img/apple/sheets/16.png
https://unpkg.com/emoji-datasource-google@7.0.1/img/google/sheets/16.png
https://unpkg.com/emoji-datasource-twitter@7.0.1/img/twitter/sheets/16.png
https://unpkg.com/emoji-datasource-facebook@7.0.1/img/facebook/sheets/16.png

**Comment by iamcal** [comment]
I've re-published the 6.1.1 image packages for backward compatibility, and they can now be loaded via UNPKG. Apologies for the inconvenience.

https://unpkg.com/emoji-datasource-apple@6.1.1/img/apple/sheets/16.png

**Comment by yagudaev** [comment]
Thank you @iamcal ❤️. It's been amazing having this on my site emojination.io.

Even managed to contribute a little to open source: https://github.com/missive/emoji-mart/pull/506

**Comment by iamcal** [comment]
Glad you've found it useful!
