### ISSUE TITLE
Add to bower

### ISSUE THREAD

**Issue by chanthus** [iamcal/emoji-data#21]
Hello!

Just wondering if you would be able to publish this repository through bower. Or maybe you have a good reason why you haven't done that already. Any thoughts?

Thanks

**Comment by iamcal** [comment]
I'm definitely open to doing it, but it's not currently set up to be super usable - it would need to include the images in the bower package and I don't know how to do that. It's something I'd _like_ to do if I have the time to figure it out (npm too)

**Comment by chanthus** [comment]
Ah cool. Nothing urgent. So, great to know that it's on the roadmap.

**Comment by jmeas** [comment]
> it would need to include the images in the bower package and I don't know how to do that.

Since Bower works through git, I'd expect that if the images are in the git repo then they should be installed when a user Bower installs. So it should just be a matter of adding a Bower.json to this repo and running `bower register emoji-data git@github.com:iamcal/emoji-data.git` from the command line.

**Comment by iamcal** [comment]
this is now done. unlike the npm package, it contains both the spritesheets and the individual images
