### ISSUE TITLE
Unicode 9 support!

### ISSUE THREAD

**Issue by autopulated** [iamcal/emoji-data#59]
Twemoji has been updated to include unicode 9 emoji – is it possible to re-build and include that data now?

**Comment by jhuckaby** [comment]
I totally understand the complexity of adding those new double-wide Emoji into a spritesheet, but would it be possible to just add the single-wide Emoji in Unicode 9.0?  Just these here:

🤣 🤤 🤠 🤡 🤥 🤢 🤧 🤶 🤴 🤵 🤰 🤦 🤷 🕺 🤺 🤸 🤼 🤽 🤾 🤹 🤳 🤞 🤙 🤛 🤜 🤚 🤝 🖤 🦍 🦊 🦌 🦏 🦇 🦅 🦆 🦉 🦎 🦈 🦐 🦑 🦋 🥀 🥝 🥑 🥔 🥕 🥒 🥜 🥐 🥖 🥞 🥓 🥙 🥚 🥘 🥗 🥛 🥂 🥃 🥄 🛴 🛵 🛑 🛶 🥇 🥈 🥉 🥊 🥋 🥅 🥁 🛒

I personally have no need for the silly double-wide ones.  I just want some of the extremely popular ones in U9.0 like :rofl: and 🤢 .

Reference:
http://www.unicode.org/emoji/charts/emoji-versions.html#v9.0_2016

Thanks for a wonderful library!

**Comment by Crissov** [comment]
I think what @jhuckaby is referring to as _double-wide_ emojis are the various kinds of *emoji sequences* described in [UTS#51](http://unicode.org/reports/tr51/#Emoji_Sequences) alias Emoji *X*.0 (currently 4.0 and [5.0](http://unicode.org/reports/tr51/proposed.html) [beta](http://unicode.org/emoji/charts-beta/emoji-released.html)), whereas _single-wide_ emojis are code-points defined in the Unicode Standard (currently 9.0 and [10.0 beta](http://unicode.org/alloc/Pipeline.html)). The former should indeed be part of a separate issue since they are harder to get right.

**Comment by iamcal** [comment]
we already support several sequences (from emoji 3.0), but not the latest. closing this in favor of #77 which is the same thing
