### ISSUE TITLE
Publish npm

### ISSUE THREAD

**Issue by sugarshin** [iamcal/emoji-data#84]
Hi,

Please publish latest version to npm. thanks.

**Comment by joehiggs** [comment]
+1

**Comment by timabbott** [comment]
I'd also find this useful, since it makes it easier to keep track of when new releases are available without having to check manually.

**Comment by iamcal** [comment]
it's currently broken because the package (just with the spritesheets, not the individual images) are too large :(

**Comment by iamcal** [comment]
my plan it to break it up into multiple packages, one per image set

**Comment by jmeas** [comment]
@iamcal have you considered merging all of these projects into a monorepo? The benefits that you may see would be:

- no sub modules, which is ever-so-slightly less complexity
- everything in one place makes it easy to rearrange files for publishing to npm
- tools like lerna can make tasks like building/testing/publishing into a single command

I know you've mentioned in the past that you don't use npm, so I can imagine how it might be frustrating to have to manage all of these different packages if there are many steps to doing a release. If you think that could be the case, then a monorepo could be worth looking into. If you've got some other plan to automate it, or don't think the work will be too much, then no worries.

I really appreciate that you're doing this, by the way! Thank you!

**Comment by iamcal** [comment]
I assume you mean this repo and the JS one? There are about 10 different language versions which rely on this datasource, only some of which are by me, so I don't have the option to merge.

Beyond that, the problems with publishing to npm are:

* The whole emoji-data report is just too big for npm
* npm does not give you an easy way to publish multiple packages from a single repo (i'm scripting that now)
* I constantly hit a 2+ year old npm bug which means publishing fails due to a stack overflow (the only advice in the issue threads is to not use npm!)

I'm close to having one base package on npm (with minimal images), plus one per image set which contains everything. If I can get around the stack overflow problems, it'll be done.

**Comment by iamcal** [comment]
v2.5.2 is now on npm. More details here: https://github.com/iamcal/emoji-data#installation
