### ISSUE TITLE
Expectations around variation selector handling

### ISSUE THREAD

**Issue by ticky** [iamcal/emoji-data#89]
Hi there,

I’m currently implementing some work based upon your emoji data set.

The data set here doesn’t appear to take into consideration variation selector requirements for certain code points. As far as the data here is concerned, `U+00AE ®` is an emoji just as much as `U+00AE-U+FE0F ®️` is.

Despite a “variations” key existing for some emoji, with `U+FE0F VARIATION SELECTOR-16` included, this being present does not accurately indicate a character’s default `Emoji_Presentation` value!

I’d suggest either that this data set should provide the `Emoji_Presentation` data, or the `unified` values should include the `U+FE0F VARIATION SELECTOR-16` in cases where the character’s `Emoji_Presentation` is `False`.

I’ve worked around this limitation by making use of a regular expression which takes variation selectors into account correctly for matching, but this isn’t ideal, as it means my application ultimately has two sources of truth!

For your reference;
* [Chart of emoji code points listed by their default presentation](http://unicode.org/emoji/charts/emoji-style.html)
* [_Unicode Technical Standard 51_’s Presentation Style section](http://unicode.org/reports/tr51/index.html#Presentation_Style)

Thanks for your work on this invaluable data set! 💜

**Comment by iamcal** [comment]
The explanation is that it's like this for historical and backward compatibility reasons - originally iOS did not use the variation selector at all (it did not exist yet), so many codepoints rendered as emoji when no selector was present. As a result, iOS now uses `FE0F` for emoji-mode and `FE0E` for text mode, while other platforms use `FE0F` for emoji node and no selector for text mode. Because of this incompatibility, it's up to implementors to choose what happens when a bare maybe-emoji codepoint is presented.

**Comment by iamcal** [comment]
Including the emoji properties in the output data is probably a good idea 👍

**Comment by iamcal** [comment]
this has been fixed in PR #100 which will become release 4.0.0

i now use the fully-qualified version (including modifier) as the main codepoint sequence, with non-qualified versions appearing as an optional property. all images have been renamed to reflect this.
