### ISSUE TITLE
Four Apple Emoji present in sheet but missing individually

### ISSUE THREAD

**Issue by samkelleher** [iamcal/emoji-data#91]
The dataset lists 4 emoji which are present and visible in the sheet, but missing as individual files, specifically the Apple dataset.

They are not present in the underlying Apple supported set (ie they are not present natively). All but the UN flag are actually just the black 'wingdings' style ones rather than actual emoji on Apple.

```
23CF (Eject Symbol [x: 0, y: 17]) 
1F1FA-1F1F3 (Regional Indicator Symbol Letters UN [x: 36, y: 5])
2640 (Female Sign [x: 1, y: 18])
2642 (Male Sign [x: 1, y: 19])
```

Looks like when the sheet is generated, they are substituted for something else, but these subtritutions are not present in the individual output.

Use case, in my application I don't use the large sheet, but reference the images individual when needed. Thus these ones are missing despite having as has_image as true.

![screen shot 2017-06-13 at 4 14 28 pm](https://user-images.githubusercontent.com/277884/27089821-68c07dea-5053-11e7-95a2-c5209c0906cf.png)

This is how they look, first from the sheet, second natively, third as the individual image.

These are the only 4 emoji in the entire set that are missing individually.

**Comment by iamcal** [comment]
This is on purpose. Because those images don't exist in the apple font, there's no individual image. This is reflected in the JSON data - `emoji.has_apple_img == false`. The other image sets are missing more than apple.

To make using the sheets slightly easier, I substitute the missing images with ones from other sets. Any code using the data but not using the sheets will need to handle this fail-over manually.
